MODEL_3_5 = 'gpt-3.5-turbo-16k'
MODEL_4_0 = 'gpt-4-1106-preview'
OPENAI_ORG = '<ORG_ID>'
OPENAI_KEY = '<OPENAI_KEY>'

HPOGS_ANNOT_FOLDER = '<PATH_TO_FOLDER>'
HPOGS_TEXT_FOLDER = '<PATH_TO_FOLDER>'

BIOCGS_ANNOT_FOLDER = '<PATH_TO_FOLDER>'
BIOCGS_TEXT_FOLDER = '<PATH_TO_FOLDER>'
